WIDTH = 800
HEIGHT = 600
map_width = 120
map_height = 80
tile_size = 16
model = "model_1"
pants = "pants_1"
boots = "boots_1"
shirt = "shirt_1"
hair = "hair_1"
helmet = "helmet_1"
shield = "shield_1"
weapon = "none"
zoom_level = 2
player_speed = 1.5

background = {
    'grass_1':{'img':"town/tiles/grass_green/tile_0000.png"},
    'grass_2':{'img':"town/tiles/grass_green/tile_0001.png"},
    'grass_3':{'img':"town/tiles/grass_green/tile_0002.png"},
    'grass_4':{'img':"town/tiles/grass_green/tile_0017.png"}
}

castle = {
    'gate_ground_top':{'img':"town/tiles/grass_path/tile_0025.png",'pos_x':(5,7),'pos_y':(6,7)},
    'gate_ground_bottom':{'img':"town/tiles/grass_path/tile_0037.png",'pos_x':(5,7),'pos_y':(7,8)},
    'gate_top_left':{'img':"town/tiles/castle/tile_0111.png", 'pos_x':(5,6),'pos_y':(6,7)},
    'gate_top_right':{'img':"town/tiles/castle/tile_0112.png", 'pos_x':(6,7),'pos_y':(6,7)},
    'gate_bottom_left':{'img':"town/tiles/castle/tile_0123.png", 'pos_x':(5,6),'pos_y':(7,8)},
    'gate_bottom_right':{'img':"town/tiles/castle/tile_0124.png", 'pos_x':(6,7),'pos_y':(7,8)},
    'keep_wall':{'img':"town/tiles/castle/tile_0126.png", 'pos_x':(4,8),'pos_y':(5,6)},
    'tower_left_wall':{'img':"town/tiles/castle/tile_0126.png", 'pos_x':(0,4),'pos_y':(2,8)},
    'tower_right_wall':{'img':"town/tiles/castle/tile_0126.png", 'pos_x':(8,12),'pos_y':(2,8)},

    'keep_wall_lower_left':{'img':"town/tiles/castle/tile_0126.png", 'pos_x':(4,5),'pos_y':(6,8)},
    'keep_wall_lower_right':{'img':"town/tiles/castle/tile_0126.png", 'pos_x':(7,8),'pos_y':(6,8)},
    'keep_wall_left':{'img':"town/tiles/castle/tile_0124.png", 'pos_x':(3,4),'pos_y':(2,8)},
    'keep_wall_right':{'img':"town/tiles/castle/tile_0123.png", 'pos_x':(8,9),'pos_y':(2,8)},

    'keep_top_top_left':{'img':"town/tiles/castle/tile_0096.png", 'pos_x':(4,5),'pos_y':(3,4)},
    'keep_top_top':{'img':"town/tiles/castle/tile_0097.png", 'pos_x':(5,7),'pos_y':(3,4)},
    'keep_top_top_right':{'img':"town/tiles/castle/tile_0098.png", 'pos_x':(7,8),'pos_y':(3,4)},
    'keep_top_bottom_left':{'img':"town/tiles/castle/tile_0120.png", 'pos_x':(4,5),'pos_y':(4,5)},
    'keep_top_bottom':{'img':"town/tiles/castle/tile_0121.png", 'pos_x':(5,7),'pos_y':(4,5)},
    'keep_top_bottom_right':{'img':"town/tiles/castle/tile_0122.png", 'pos_x':(7,8),'pos_y':(4,5)},

    'tower_left_top_top_left':{'img':"town/tiles/castle/tile_0096.png", 'pos_x':(0,1),'pos_y':(0,1)},
    'tower_left_top_top':{'img':"town/tiles/castle/tile_0097.png", 'pos_x':(1,3),'pos_y':(0,1)},
    'tower_left_top_top_right':{'img':"town/tiles/castle/tile_0098.png", 'pos_x':(3,4),'pos_y':(0,1)},
    'tower_left_top_bottom_left':{'img':"town/tiles/castle/tile_0120.png", 'pos_x':(0,1),'pos_y':(1,2)},
    'tower_left_top_bottom':{'img':"town/tiles/castle/tile_0121.png", 'pos_x':(1,3),'pos_y':(1,2)},
    'tower_left_top_bottom_right':{'img':"town/tiles/castle/tile_0122.png", 'pos_x':(3,4),'pos_y':(1,2)},
    'tower_left_wall_left':{'img':"town/tiles/castle/tile_0123.png", 'pos_x':(0,1),'pos_y':(2,8)},
    

    'tower_right_top_top_left':{'img':"town/tiles/castle/tile_0096.png", 'pos_x':(8,9),'pos_y':(0,1)},
    'tower_right_top_top':{'img':"town/tiles/castle/tile_0097.png", 'pos_x':(9,11),'pos_y':(0,1)},
    'tower_right_top_top_right':{'img':"town/tiles/castle/tile_0098.png", 'pos_x':(11,12),'pos_y':(0,1)},
    'tower_right_top_bottom_left':{'img':"town/tiles/castle/tile_0120.png", 'pos_x':(8,9),'pos_y':(1,2)},
    'tower_right_top_bottom':{'img':"town/tiles/castle/tile_0121.png", 'pos_x':(9,11),'pos_y':(1,2)},
    'tower_right_top_bottom_right':{'img':"town/tiles/castle/tile_0122.png", 'pos_x':(11,12),'pos_y':(1,2)},
    'tower_left_wall_right':{'img':"town/tiles/castle/tile_0124.png", 'pos_x':(11,12),'pos_y':(2,8)},
}

brick_house = {
    'wall':{'img':"town/tiles/building_brick/tile_0073.png", 'pos_x':(1,4),'pos_y':(2,4)},
    'wall_left':{'img':"town/tiles/building_brick/tile_0072.png",'pos_x':(0,1),'pos_y':(2,4)},
    'wall_right':{'img':"town/tiles/building_brick/tile_0075.png",'pos_x':(4,5),'pos_y':(2,4)},
    'door':{'img':"town/tiles/building_brick/tile_0085.png",'pos_x':(2,3),'pos_y':(3,4)},
    'roof_top':{'img':"town/tiles/roof_stone/tile_0049.png",'pos_x':(1,4),'pos_y':(0,1)},
    'roof_bottom':{'img':"town/tiles/roof_stone/tile_0061.png",'pos_x':(1,4),'pos_y':(1,2)},
    'roof_left':{'img':"town/tiles/roof_stone/tile_0060.png",'pos_x':(0,1),'pos_y':(1,2)},
    'roof_right':{'img':"town/tiles/roof_stone/tile_0062.png",'pos_x':(4,5),'pos_y':(1,2)},
    'roof_left_corner':{'img':"town/tiles/roof_stone/tile_0048.png",'pos_x':(0,1),'pos_y':(0,1)},
    'roof_right_corner':{'img':"town/tiles/roof_stone/tile_0050.png",'pos_x':(4,5),'pos_y':(0,1)},
    'roof_arch':{'img':"town/tiles/roof_stone/tile_0063.png",'pos_x':(2,3),'pos_y':(1,2)}
}

trees = {
    'tree_center':{'img':"town/tiles/trees_green/tile_0019.png"},
    'tree_bottom':{'img':"town/tiles/trees_green/tile_0031.png"},
    'tree_top':{'img':"town/tiles/trees_green/tile_0007.png"},
    'tree_left':{'img':"town/tiles/trees_green/tile_0020.png"},
    'tree_right':{'img':"town/tiles/trees_green/tile_0018.png"}
}

stone_house = {
    'wall':{'img':"town/tiles/building_stone/tile_0077.png", 'pos_x':(1,4),'pos_y':(2,4)},
    'wall_left':{'img':"town/tiles/building_stone/tile_0076.png",'pos_x':(0,1),'pos_y':(2,4)},
    'wall_right':{'img':"town/tiles/building_stone/tile_0079.png",'pos_x':(4,5),'pos_y':(2,4)},
    'door':{'img':"town/tiles/building_stone/tile_0089.png",'pos_x':(2,3),'pos_y':(3,4)},
    'roof_top':{'img':"town/tiles/roof_brick/tile_0053.png",'pos_x':(1,4),'pos_y':(0,1)},
    'roof_bottom':{'img':"town/tiles/roof_brick/tile_0065.png",'pos_x':(1,4),'pos_y':(1,2)},
    'roof_left':{'img':"town/tiles/roof_brick/tile_0064.png",'pos_x':(0,1),'pos_y':(1,2)},
    'roof_right':{'img':"town/tiles/roof_brick/tile_0066.png",'pos_x':(4,5),'pos_y':(1,2)},
    'roof_left_corner':{'img':"town/tiles/roof_brick/tile_0052.png",'pos_x':(0,1),'pos_y':(0,1)},
    'roof_right_corner':{'img':"town/tiles/roof_brick/tile_0054.png",'pos_x':(4,5),'pos_y':(0,1)},
    'roof_arch':{'img':"town/tiles/roof_brick/tile_0067.png",'pos_x':(2,3),'pos_y':(1,2)}
}

item_data = {
    "none": {"pos": (34, 0),   "category": "none", "stats": {"defense": 0, "speed": 0}},
    
    #model
    "model_1":{"pos":(0,0),"category":"model", 'stats': {'defense': 0, 'speed': 0}},
    "model_2":{"pos":(0,17),"category":"model", 'stats': {'defense': 0, 'speed': 0}},
    "model_3":{"pos":(0,34),"category":"model",'stats': {'defense': 0, 'speed': 0}},
    "model_4":{"pos":(17,0),"category":"model",'stats': {'defense': 0, 'speed': 0}},
    "model_5":{"pos":(17,17),"category":"model",'stats': {'defense': 0, 'speed': 0}},
    "model_6":{"pos":(17,34),"category":"model",'stats': {'defense': 0, 'speed': 0}},

    #hair
    "hair_1":{'pos': (323, 0), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_2":{'pos': (323, 17), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_3":{'pos': (323, 34), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_4":{'pos': (323, 51), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_5":{'pos': (323, 68), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_6":{'pos': (323, 85), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_7":{'pos': (323, 102), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_8":{'pos': (323, 119), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_9":{'pos': (323, 136), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_10":{'pos': (323, 153), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_11":{'pos': (323, 170), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_12":{'pos': (323, 187), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_13":{'pos': (340, 0), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_14":{'pos': (340, 17), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_15":{'pos': (340, 34), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_16":{'pos': (340, 51), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_17":{'pos': (340, 68), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_18":{'pos': (340, 85), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_19":{'pos': (340, 102), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_20":{'pos': (340, 119), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_21":{'pos': (340, 136), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_22":{'pos': (340, 153), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_23":{'pos': (340, 170), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_24":{'pos': (340, 187), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_25":{'pos': (357, 0), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_26":{'pos': (357, 17), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_27":{'pos': (357, 34), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_28":{'pos': (357, 51), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_29":{'pos': (357, 68), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_30":{'pos': (357, 85), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_31":{'pos': (357, 102), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_32":{'pos': (357, 119), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_33":{'pos': (357, 136), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_34":{'pos': (357, 153), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_35":{'pos': (357, 170), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_36":{'pos': (357, 187), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_37":{'pos': (374, 0), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_38":{'pos': (374, 17), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_39":{'pos': (374, 34), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_40":{'pos': (374, 51), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_41":{'pos': (374, 68), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_42":{'pos': (374, 85), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_43":{'pos': (374, 102), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_44":{'pos': (374, 119), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_45":{'pos': (374, 136), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_46":{'pos': (374, 153), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_47":{'pos': (374, 170), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_48":{'pos': (374, 187), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_49":{'pos': (391, 0), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_50":{'pos': (391, 17), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_51":{'pos': (391, 34), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_52":{'pos': (391, 51), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_53":{'pos': (391, 68), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_54":{'pos': (391, 85), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_55":{'pos': (391, 102), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_56":{'pos': (391, 119), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_57":{'pos': (408, 0), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_58":{'pos': (408, 17), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_59":{'pos': (408, 34), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_60":{'pos': (408, 51), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_61":{'pos': (408, 68), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_62":{'pos': (408, 85), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_63":{'pos': (408, 102), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_64":{'pos': (408, 119), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_65":{'pos': (425, 0), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_66":{'pos': (425, 17), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_67":{'pos': (425, 34), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_68":{'pos': (425, 51), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_69":{'pos': (425, 68), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_70":{'pos': (425, 85), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_71":{'pos': (425, 102), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_72":{'pos': (425, 119), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_73":{'pos': (442, 0), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_74":{'pos': (442, 17), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_75":{'pos': (442, 34), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_76":{'pos': (442, 51), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_77":{'pos': (442, 68), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_78":{'pos': (442, 85), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_79":{'pos': (442, 102), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    "hair_80":{'pos': (442, 119), 'category': 'hair', 'stats': {'defense': 0, 'speed': 0}},
    
    # helmet
    "helmet_1":{'pos': (476, 0), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_2":{'pos': (476, 17), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_3":{'pos': (476, 34), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_4":{'pos': (476, 51), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_5":{'pos': (476, 68), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_6":{'pos': (476, 85), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_7":{'pos': (476, 102), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_8":{'pos': (476, 119), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_9":{'pos': (476, 136), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_10":{'pos': (493, 0), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_11":{'pos': (493, 17), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_12":{'pos': (493, 34), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_13":{'pos': (493, 51), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_14":{'pos': (493, 68), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_15":{'pos': (493, 85), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_16":{'pos': (493, 102), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_17":{'pos': (493, 119), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_18":{'pos': (493, 136), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_19":{'pos': (510, 0), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_20":{'pos': (510, 17), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_21":{'pos': (510, 34), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_22":{'pos': (510, 51), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_23":{'pos': (510, 68), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_24":{'pos': (510, 85), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_25":{'pos': (510, 102), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_26":{'pos': (510, 119), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_27":{'pos': (510, 136), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_28":{'pos': (527, 0), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_29":{'pos': (527, 17), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_30":{'pos': (527, 34), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_31":{'pos': (527, 51), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_32":{'pos': (527, 68), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_33":{'pos': (527, 85), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_34":{'pos': (527, 102), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_35":{'pos': (527, 119), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},
    "helmet_36":{'pos': (527, 136), 'category': 'helmet', 'stats': {'defense': 1, 'speed': 0}},

    # pants
    "pants_1":  {"pos": (51, 0),   "category": "pants", "stats": {"defense": 1, "speed": 0}},
    "pants_2":  {"pos": (51, 17),  "category": "pants", "stats": {"defense": 1, "speed": 0}},
    "pants_3":   {"pos": (51, 34),  "category": "pants", "stats": {"defense": 5, "speed": -1}},
    "pants_4":{"pos": (51, 51),  "category": "pants", "stats": {"defense": 2, "speed": 1}},
    "pants_5":    {"pos": (51, 85),  "category": "pants", "stats": {"defense": 1, "speed": 0}},
    "pants_6":   {"pos": (51, 102), "category": "pants", "stats": {"defense": 1, "speed": 0}},
    "pants_7": {"pos": (51, 119), "category": "pants", "stats": {"defense": 1, "speed": 0}},
    "pants_8":  {"pos": (51, 136), "category": "pants", "stats": {"defense": 1, "speed": 0}},

    # dresses
    "dress_1":   {"pos": (51, 68),  "category": "dress", "stats": {"defense": 1, "speed": 1}},
    "dress_2":  {"pos": (51, 170), "category": "dress", "stats": {"defense": 1, "speed": 0}},
    "dress_3":    {"pos": (68, 68),  "category": "dress", "stats": {"defense": 1, "speed": 0}},
    "dress_4": {"pos": (51, 170), "category": "dress", "stats": {"defense": 1, "speed": 0}},

    # boots
    "boots_1":  {"pos": (68, 0),   "category": "boots", "stats": {"defense": 1, "speed": 0}},
    "boots_2":  {"pos": (68, 17),  "category": "boots", "stats": {"defense": 1, "speed": 0}},
    "boots_3":   {"pos": (68, 34),  "category": "boots", "stats": {"defense": 3, "speed": -1}},
    "boots_4":{"pos": (68, 51),  "category": "boots", "stats": {"defense": 1, "speed": 1}},
    "boots_5":    {"pos": (68, 85),  "category": "boots", "stats": {"defense": 1, "speed": 0}},
    "boots_6":   {"pos": (68, 102), "category": "boots", "stats": {"defense": 1, "speed": 0}},
    "boots_7": {"pos": (68, 119), "category": "boots", "stats": {"defense": 1, "speed": 0}},
    "boots_8":  {"pos": (68, 136), "category": "boots", "stats": {"defense": 1, "speed": 0}},

     # shirts
    "shirt_1": {"pos": (102, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_2": {"pos": (102, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_3": {"pos": (102, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_4": {"pos": (102, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_5": {"pos": (102, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_6": {"pos": (102, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_7": {"pos": (102, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_8": {"pos": (102, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_9": {"pos": (102, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_10": {"pos": (102, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_11": {"pos": (102, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_12": {"pos": (119, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_13": {"pos": (119, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_14": {"pos": (119, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_15": {"pos": (119, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_16": {"pos": (119, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_17": {"pos": (119, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_18": {"pos": (119, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_19": {"pos": (119, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_20": {"pos": (119, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_21": {"pos": (119, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_22": {"pos": (119, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_23": {"pos": (136, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_24": {"pos": (136, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_25": {"pos": (136, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_26": {"pos": (136, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_27": {"pos": (136, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_28": {"pos": (136, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_29": {"pos": (136, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_30": {"pos": (136, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_31": {"pos": (136, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_32": {"pos": (136, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_33": {"pos": (136, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_34": {"pos": (153, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_35": {"pos": (153, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_36": {"pos": (153, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_37": {"pos": (153, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_38": {"pos": (153, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_39": {"pos": (153, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_40": {"pos": (153, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_41": {"pos": (153, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_42": {"pos": (153, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_43": {"pos": (153, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_44": {"pos": (153, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_45": {"pos": (170, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_46": {"pos": (170, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_47": {"pos": (170, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_48": {"pos": (170, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_49": {"pos": (170, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_50": {"pos": (170, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_51": {"pos": (170, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_52": {"pos": (170, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_53": {"pos": (170, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_54": {"pos": (170, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_55": {"pos": (170, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_56": {"pos": (187, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_57": {"pos": (187, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_58": {"pos": (187, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_59": {"pos": (187, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_60": {"pos": (187, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_61": {"pos": (187, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_62": {"pos": (187, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_63": {"pos": (187, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_64": {"pos": (187, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_65": {"pos": (187, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_66": {"pos": (187, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_67": {"pos": (204, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_68": {"pos": (204, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_69": {"pos": (204, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_70": {"pos": (204, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_71": {"pos": (204, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_72": {"pos": (204, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_73": {"pos": (204, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_74": {"pos": (204, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_75": {"pos": (204, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_76": {"pos": (204, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_77": {"pos": (204, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_78": {"pos": (221, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_79": {"pos": (221, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_80": {"pos": (221, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_81": {"pos": (221, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_82": {"pos": (221, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_83": {"pos": (221, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_84": {"pos": (221, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_85": {"pos": (221, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_86": {"pos": (221, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_87": {"pos": (221, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_88": {"pos": (221, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_89": {"pos": (238, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_90": {"pos": (238, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_91": {"pos": (238, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_92": {"pos": (238, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_93": {"pos": (238, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_94": {"pos": (238, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_95": {"pos": (238, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_96": {"pos": (238, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_97": {"pos": (238, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_98": {"pos": (238, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_99": {"pos": (238, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_100": {"pos": (255, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_101": {"pos": (255, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_102": {"pos": (255, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_103": {"pos": (255, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_104": {"pos": (255, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_105": {"pos": (255, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_106": {"pos": (255, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_107": {"pos": (255, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_108": {"pos": (255, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_109": {"pos": (255, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_110": {"pos": (255, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_111": {"pos": (272, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_112": {"pos": (272, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_113": {"pos": (272, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_114": {"pos": (272, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_115": {"pos": (272, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_116": {"pos": (272, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_117": {"pos": (272, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_118": {"pos": (272, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_119": {"pos": (272, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_120": {"pos": (272, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_121": {"pos": (272, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_122": {"pos": (289, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_123": {"pos": (289, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_124": {"pos": (289, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_125": {"pos": (289, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_126": {"pos": (289, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_127": {"pos": (289, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_128": {"pos": (289, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_129": {"pos": (289, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_130": {"pos": (289, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_131": {"pos": (289, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_132": {"pos": (289, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_133": {"pos": (306, 0), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_134": {"pos": (306, 17), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_135": {"pos": (306, 34), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_136": {"pos": (306, 51), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_137": {"pos": (306, 68), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_138": {"pos": (306, 85), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_139": {"pos": (306, 102), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_140": {"pos": (306, 119), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_141": {"pos": (306, 136), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_142": {"pos": (306, 153), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    "shirt_143": {"pos": (306, 170), "category": "shirt", "stats": {"defense": 1, "speed": 0}},
    
    # shield
    "shield_1":{'pos': (561, 0), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_2":{'pos': (561, 17), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_3":{'pos': (561, 34), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_4":{'pos': (561, 51), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_5":{'pos': (561, 68), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_6":{'pos': (561, 85), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_7":{'pos': (561, 102), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_8":{'pos': (561, 119), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_9":{'pos': (561, 136), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_10":{'pos': (578, 0), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_11":{'pos': (578, 17), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_12":{'pos': (578, 34), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_13":{'pos': (578, 51), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_14":{'pos': (578, 68), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_15":{'pos': (578, 85), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_16":{'pos': (578, 102), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_17":{'pos': (578, 119), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_18":{'pos': (578, 136), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_19":{'pos': (595, 0), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_20":{'pos': (595, 17), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_22":{'pos': (595, 51), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_23":{'pos': (595, 68), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_25":{'pos': (595, 102), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_26":{'pos': (595, 119), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_28":{'pos': (612, 0), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_29":{'pos': (612, 17), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_31":{'pos': (612, 51), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_32":{'pos': (612, 68), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_34":{'pos': (612, 102), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_35":{'pos': (612, 119), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_37":{'pos': (629, 0), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_38":{'pos': (629, 17), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_39":{'pos': (629, 34), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_40":{'pos': (629, 51), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_41":{'pos': (629, 68), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_42":{'pos': (629, 85), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_43":{'pos': (629, 102), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_44":{'pos': (629, 119), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_45":{'pos': (629, 136), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_46":{'pos': (646, 0), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_47":{'pos': (646, 17), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_48":{'pos': (646, 34), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_49":{'pos': (646, 51), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_50":{'pos': (646, 68), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_51":{'pos': (646, 85), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_52":{'pos': (646, 102), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_53":{'pos': (646, 119), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_54":{'pos': (646, 136), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_55":{'pos': (663, 0), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_56":{'pos': (663, 17), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_58":{'pos': (663, 51), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_59":{'pos': (663, 68), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_61":{'pos': (663, 102), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_62":{'pos': (663, 119), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_64":{'pos': (680, 0), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_65":{'pos': (680, 17), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_67":{'pos': (680, 51), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_68":{'pos': (680, 68), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_70":{'pos': (680, 102), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    "shield_71":{'pos': (680, 119), 'category': 'shield', 'stats': {'defense': 5, 'speed': -2}},
    
    # weapons
    "weapon_1":{'pos': (714, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_2":{'pos': (714, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_3":{'pos': (714, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_4":{'pos': (714, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_5":{'pos': (714, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_6":{'pos': (714, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_7":{'pos': (714, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_8":{'pos': (714, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_9":{'pos': (714, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_10":{'pos': (714, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_11":{'pos': (731, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_12":{'pos': (731, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_13":{'pos': (731, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_14":{'pos': (731, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_15":{'pos': (731, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_16":{'pos': (731, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_17":{'pos': (731, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_18":{'pos': (731, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_19":{'pos': (731, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_20":{'pos': (731, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_21":{'pos': (748, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_22":{'pos': (748, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_23":{'pos': (748, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_24":{'pos': (748, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_25":{'pos': (748, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_26":{'pos': (748, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_27":{'pos': (748, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_28":{'pos': (748, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_29":{'pos': (748, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_30":{'pos': (748, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_31":{'pos': (765, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_32":{'pos': (765, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_33":{'pos': (765, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_34":{'pos': (765, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_35":{'pos': (765, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_36":{'pos': (765, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_37":{'pos': (765, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_38":{'pos': (765, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_39":{'pos': (765, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_40":{'pos': (765, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_41":{'pos': (782, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_42":{'pos': (782, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_43":{'pos': (782, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_44":{'pos': (782, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_45":{'pos': (782, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_46":{'pos': (782, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_47":{'pos': (782, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_48":{'pos': (782, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_49":{'pos': (782, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_50":{'pos': (782, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_51":{'pos': (799, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_52":{'pos': (799, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_53":{'pos': (799, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_54":{'pos': (799, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_55":{'pos': (799, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_56":{'pos': (799, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_57":{'pos': (799, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_58":{'pos': (799, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_59":{'pos': (799, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_60":{'pos': (799, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_61":{'pos': (816, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_62":{'pos': (816, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_63":{'pos': (816, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_64":{'pos': (816, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_65":{'pos': (816, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_66":{'pos': (816, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_67":{'pos': (816, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_68":{'pos': (816, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_69":{'pos': (816, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_70":{'pos': (816, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_71":{'pos': (833, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_72":{'pos': (833, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_73":{'pos': (833, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_74":{'pos': (833, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_75":{'pos': (833, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_76":{'pos': (833, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_77":{'pos': (833, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_78":{'pos': (833, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_79":{'pos': (833, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_80":{'pos': (833, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_81":{'pos': (850, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_82":{'pos': (850, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_83":{'pos': (850, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_84":{'pos': (850, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_85":{'pos': (850, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_86":{'pos': (850, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_87":{'pos': (850, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_88":{'pos': (850, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_89":{'pos': (850, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_90":{'pos': (850, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_91":{'pos': (867, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_92":{'pos': (867, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_93":{'pos': (867, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_94":{'pos': (867, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_95":{'pos': (867, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_96":{'pos': (867, 85), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_97":{'pos': (867, 102), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_98":{'pos': (867, 119), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_99":{'pos': (867, 136), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_100":{'pos': (867, 153), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_101":{'pos': (884, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_102":{'pos': (884, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_103":{'pos': (884, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_104":{'pos': (884, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_105":{'pos': (884, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_106":{'pos': (901, 0), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_107":{'pos': (901, 17), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_108":{'pos': (901, 34), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_109":{'pos': (901, 51), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
    "weapon_110":{'pos': (901, 68), 'category': 'weapon', 'stats': {'attack': 3, 'speed': -1}},
}